name: Convert Markdown to PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert English Markdown to PDF
        run: |
          mkdir -p pdf/english
          for file in English/**/*.md; do
            [ -e "$file" ] || continue
            pandoc "$file" -o "pdf/english/$(basename "${file%.md}.pdf")"
          done

      - name: Convert Turkish Markdown to PDF
        run: |
          mkdir -p pdf/turkce
          for file in Turkce/**/*.md; do
            [ -e "$file" ] || continue
            pandoc "$file" -o "pdf/turkce/$(basename "${file%.md}.pdf")"
          done

      - name: List generated PDF files
        run: |
          echo "Generated PDF files:"
          find pdf -type f -name "*.pdf"

      - name: Upload PDF files
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: pdf/
